version: 2
build:
  image: latest
python:
  version: "3.11"
  install:
    - method: pip
      path: .
      editable: true
    - requirements: docs/requirements.txt
sphinx:
  configuration: docs/conf.py

